on:
  pull_request:
  push:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  main_build:
    runs-on: ubuntu-24.04
    name: Sequential build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Main build
        id: build
        uses: ./.github/actions
      
      - name: Publish Python Test Results
        uses: dorny/test-reporter@v2
        if: always()  # ensures it runs even if tests fail
        with:
          name: JUnit Tests
          path: python-report.xml
          reporter: java-junit
      
      - uses: actions/upload-artifact@v4
        if: always()  # ensures it runs even if tests fail
        with:
          name: py package
          path: dist/motoko_cli-*.tar.gz
      
      - name: Publish to PyPI
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          twine upload dist/motoko_cli-*.tar.gz
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
